cv_project/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('opencv_webapp.urls'))
]

opencv_webapp/urls.py
from django.urls import path
from . import views # 같은 폴더 내의 views.py를 import
from django.conf import settings
from django.conf.urls.static import static

app_name = 'opencv_webapp'

urlpatterns = [
    path('detect_face/', views.detect_face, name='detect_face'),
    path('', views.first_view, name='first_view'),
    path('simple_upload/', views.simple_upload, name='simple_upload'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

opencv_webapp/models.py
from django.db import models

# Create your models here.
class ImageUploadModel(models.Model):
    # blank=True : Form에서 빈 채로 저장되는 것을 허용 (views.py에서 활용한 .is_valid() 함수가 검증 진행 시)
    description = models.CharField(max_length=255, blank=True)
    # upload_to : 저장될 파일의 경로를 지정 (ex. ‘images/2020/02/21/test_image.jpg’)
    document = models.ImageField(upload_to='images/%Y/%m/%d')
    # auto_now_add : 자동으로 저장되는 시점을 기준으로 현재 시간을 세팅
    uploaded_at = models.DateTimeField(auto_now_add=True)

opencv_webapp/forms.py
from django import forms
from .models import ImageUploadModel

class SimpleUploadForm(forms.Form):
    title = forms.CharField(max_length=50)

    image = forms.ImageField()

class ImageUploadForm(forms.ModelForm):
# Form을 통해 받아들여야 할 데이터가 명시되어 있는 메타 데이터 (DB 테이블을 연결)
    class Meta:
        model = ImageUploadModel
        # Form을 통해 사용자로부터 입력 받으려는 Model Class의 field 리스트
        fields = ('description', 'document', ) # uploaded_at

opencv_webapp/views.py
from django.shortcuts import render,redirect
from .forms import SimpleUploadForm,ImageUploadForm
from django.core.files.storage import FileSystemStorage
from django.conf import settings
from keras.models import load_model
from keras import utils
import numpy as np



model = load_model("./media/model/apple_qc.h5")

def first_view(request):
    return render(request,'opencv_webapp/first_view.html',{})


def simple_upload(request):
    if request.method == 'POST':
        # print(request.POST) : <QueryDict: {'csrfmiddlewaretoken': [‘~~~’], 'title': ['upload_1']}>
        # print(request.FILES) : <MultiValueDict: {'image': [<InMemoryUploadedFile: ses.jpg (image/jpeg)>]}>
        # 비어있는 Form에 사용자가 업로드한 데이터를 넣고 검증합니다.
        form = SimpleUploadForm(request.POST, request.FILES)

        if form.is_valid():
            myfile = request.FILES['image'] # 메모리에 한시적으로 저장되어있는 파일 객체
            fs = FileSystemStorage()
            filename = fs.save(myfile.name, myfile)
            # myfile.name : 'ses.jpg' (사용자가 업로드한 파일 원본의 이름)
            # filename : 'ses_UPArih4.jpg' (서버에 업로드가 끝난 파일의 이름, 중복될 시 자동으로 변경됨)
            # 서버에 업로드가 끝난 이미지 파일의 URL을 얻어내 Template에게 전달
            uploaded_file_url = fs.url(filename) # '/media/ses.jpg'

            context = {'form': form, 'uploaded_file_url': uploaded_file_url} # filled form
            return render(request, 'opencv_webapp/simple_upload.html', context)

    else: # request.method == 'GET' (DjangoBasic 실습과 유사한 방식입니다.)
        form = SimpleUploadForm()
        context = {'form': form} # empty form
        return render(request, 'opencv_webapp/simple_upload.html', context)

# Create your views here.
def detect_face(request):
    if request.method == 'POST' :
        # 비어있는 Form에 사용자가 업로드한 데이터를 넣고 검증합니다.
        form = ImageUploadForm(request.POST, request.FILES) # filled form
        if form.is_valid():
            post = form.save(commit=False)
	    # save() 함수는 DB에 저장될 ImageUploadModel 클래스 객체 자체를 리턴함 (== record 1건)
            # Form에 채워진 데이터를 DB에 실제로 저장하기 전에 변경/추가할 수 있음 (commit=False)
            # ex) post.description = papago.translate(post.description)
            post.save() # Form 객체('form')에 채워져 있는 데이터를 DB에 실제로 저장

	    # document : ImageUploadModel Class에 선언되어 있는 “document”에 해당
            imageURL = settings.MEDIA_URL + form.instance.document.name
            print('imageURL ------------------============= ', imageURL )
            img = utils.load_img('./' + imageURL, target_size=(224, 224))
            img_tensor = utils.img_to_array(img)
            img_tensor = np.expand_dims(img_tensor, axis=0)
            print('img_tensor------------------============= ', img_tensor.shape )
            img_tensor /= 255.

            pred = model.predict(img_tensor)
            print('pred------------------============= ', np.argmax(pred[0]) )
            qc_index = np.argmax(pred[0])
            qc_per = np.round(pred[0][qc_index], 4)
            print('pred------------------============= ', qc_index, qc_per)
            ll = ["특","상","보통"]
            qc = ll[qc_index]

            return render(request, 'opencv_webapp/detect_face.html', {'form':form, 'post':post, 'qc':qc, 'qc_per':qc_per})

    else:
         form = ImageUploadForm() # empty form
         return render(request, 'opencv_webapp/detect_face.html', {'form':form})

opencv_webapp/templates/opencv_webapp/detect_face.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <title>Opencv-Django</title>
  </head>
  <body>

    <form method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Upload</button>
    </form>

    {% if post %}
      <!-- post.document : ImageUploadModel Class에 선언되어 있는 "document"에 해당 (브라우저 확인) -->
      <img src="{{ post.document.url }}">
      <p>Uploaded file @ : <a href="{{ post.document.url }}">{{ post.document }}</a></p>
    {% endif %}
    <p> 이것은 fuji {{ qc }} 사과입니다 <P>
    <p><a href="{% url 'opencv_webapp:detect_face' %}">Return to home</a></p>

  </body>
</html>

opencv_webapp/templates/opencv_webapp/first_view.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <title>Opencv-Django</title>
  </head>
  <body>
    Hello world!
  </body>
</html>

opencv_webapp/templates/opencv_webapp/simple_upload.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <title>Opencv-Django</title>
  </head>
  <<body>
    <h1>사과 사진을 올려주세요.</h1>
    <form method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Upload</button>
    </form>

    {% if uploaded_file_url %}
      <img src="{{ uploaded_file_url }}">
      <p>Uploaded file @ : <a href="{{ uploaded_file_url }}">{{ uploaded_file_url }}</a></p>
    {% endif %}

    <p><a href="{% url 'opencv_webapp:simple_upload' %}">돌아가기</a></p>

  </body>>
</html>